# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Project/FPGA/Design/TCL_project/Test/Soc_A9_test/user/Hardware/bd/zynq_default/ip/zynq_default_processing_system7_0_1/zynq_default_processing_system7_0_1.xci
# IP: The module: 'zynq_default_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Project/FPGA/Design/TCL_project/Test/Soc_A9_test/user/Hardware/bd/zynq_default/ip/zynq_default_processing_system7_0_1/zynq_default_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_default_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Project/FPGA/Design/TCL_project/Test/Soc_A9_test/user/Hardware/bd/zynq_default/ip/zynq_default_processing_system7_0_1/zynq_default_processing_system7_0_1.xci
# IP: The module: 'zynq_default_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Project/FPGA/Design/TCL_project/Test/Soc_A9_test/user/Hardware/bd/zynq_default/ip/zynq_default_processing_system7_0_1/zynq_default_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_default_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
