# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/map.xdc

# Block Designs: d:/Project/FPGA/Design/TCL_project/Test/Soc_A9_test/user/Hardware/bd/zynq_default/zynq_default.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_default || ORIG_REF_NAME==zynq_default} -quiet] -quiet

# IP: d:/Project/FPGA/Design/TCL_project/Test/Soc_A9_test/user/Hardware/bd/zynq_default/ip/zynq_default_processing_system7_0_1/zynq_default_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_default_processing_system7_0_1 || ORIG_REF_NAME==zynq_default_processing_system7_0_1} -quiet] -quiet

# XDC: d:/Project/FPGA/Design/TCL_project/Test/Soc_A9_test/user/Hardware/bd/zynq_default/zynq_default_ooc.xdc
