set_property SRC_FILE_INFO {cfile:d:/Project/FPGA/Design/TCL_project/Test/Soc_A9_test/prj/xilinx/Soc_A9_test.srcs/constrs_1/new/map.xdc rfile:../../../Soc_A9_test.srcs/constrs_1/new/map.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D18 [get_ports BT_UART_rxd]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14 [get_ports BT_UART_txd]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K16 [get_ports {BT_Ctrl_tri_io[2]}]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J16 [get_ports {BT_Ctrl_tri_io[1]}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports {BT_Ctrl_tri_io[0]}]
